version: "3"
services:
  inatel-quotes-database:
    image: mysql:8
    restart: always
    container_name: "inatel-quotes-database"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
      - TZ=GMT
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - inatel-quortes-network

  inatel-quotes-api:
    build: .
    container_name: "inatel-quotes-api"
    env_file:
      - docker-compose.env
    ports:
      - 8081:8081
    networks:
      - inatel-quortes-network
    depends_on:
      - inatel-quotes-database

networks:
  inatel-quortes-network:
   driver: bridge



